BEGIN;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;

ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.candidate_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chamber_medians ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drift_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fingerprints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.legislator_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.legislators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.race_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roll_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.senate_amendment_references ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.upcoming_races ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vote_classifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vote_contexts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vote_interpretations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes_cast ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zip_district_map ENABLE ROW LEVEL SECURITY;

COMMIT;
