"""Frozen model-drafted semantic content used only by the explicit freeze command.

The normal M14B check path does not import this module or regenerate prose.
"""

from __future__ import annotations


def draft(
    *,
    policy_choice: str,
    mechanism_type: str,
    mechanism: str,
    affected_entities: list[str],
    direct_effect: str,
    plain_language_meaning: str,
    limitations: list[str],
    source_id: str,
    locator: str,
    house_action_outcome: str,
    legacy_assessment: str,
    boundary_type: str = "whole_measure",
    candidate_state: str = "candidate_complete_for_semantic_review",
) -> dict[str, object]:
    return locals()


CANDIDATE_DRAFTS = {
    "house:119:1:120": draft(
        policy_choice="Whether to make colleges and universities ineligible for Department of Homeland Security funding while they maintain specified contracts, agreements, gifts, or in-kind donations involving a Confucius Institute, the Thousand Talents Program, or a defined Chinese entity of concern.",
        mechanism_type="funding eligibility restriction with waiver",
        mechanism="A Department of Homeland Security funding restriction, lifted when the institution ends the covered relationship, with renewable one-year national-security waivers and congressional notice.",
        affected_entities=["institutions of higher education", "Department of Homeland Security", "Director of National Intelligence", "Confucius Institutes", "the Thousand Talents Program", "defined Chinese entities of concern"],
        direct_effect="The proposal would require the Department of Homeland Security to withhold its funds from a college or university that has a covered contract, agreement, gift, or in-kind donation unless the relationship ends or the Secretary grants a qualifying waiver.",
        plain_language_meaning="Colleges and universities with specified financial or contractual ties to named China-linked programs or entities would generally lose eligibility for Department of Homeland Security funding. A time-limited waiver would be available when the stated safeguards and national-security conditions are met.",
        limitations=["The proposal concerns Department of Homeland Security funds, not all federal education funding, and defines the covered relationships and entities in the bill."],
        source_id="congress-text:119:hr:881:eh", locator="section 2, XML id HFA9F75A410CF42159E1F4718909B6D73",
        house_action_outcome="passed_house_266_153", legacy_assessment="revision_would_be_required",
    ),
    "house:119:1:146": draft(
        policy_choice="Whether to add career-and-technical-education outreach and referral duties to Small Business Act programs operated by small business development centers and women's business centers.",
        mechanism_type="program service requirement",
        mechanism="Amendments to the Small Business Act duties of small business development centers and women's business centers.",
        affected_entities=["small business development centers", "women's business centers", "small businesses", "career-and-technical-education students and graduates"],
        direct_effect="The proposal would require the centers to inform small businesses about hiring career-and-technical-education graduates, tell students and graduates about center services for starting or expanding a business, and make appropriate connections between businesses and programs.",
        plain_language_meaning="Federal small-business assistance centers would add outreach linking employers with career-and-technical-education graduates and informing those students and graduates about help starting or growing a small business.",
        limitations=["The measure changes Small Business Act program duties; it does not create a general education or workforce-spending program."],
        source_id="congress-text:119:hr:1642:eh", locator="section 2, XML id H57A7FAC11CD24D039A7A7B6DED0AF3CA",
        house_action_outcome="passed_house_396_5", legacy_assessment="sufficient_unchanged",
    ),
    "house:119:1:312": draft(
        policy_choice="Whether to condition federal education assistance to public elementary and secondary schools on disclosure of foreign-source funds and contracts whose aggregate value exceeds $10,000.",
        mechanism_type="funding condition and reporting duty",
        mechanism="A condition on federal financial assistance requiring school disclosures to the Secretary of Education within 30 days.",
        affected_entities=["public elementary schools", "public secondary schools", "Secretary of Education", "foreign funding and contracting sources"],
        direct_effect="The proposal would require a covered school to submit a written disclosure identifying the foreign source, amounts, and applicable terms within 30 days after receiving funds or entering contracts above the $10,000 aggregate threshold.",
        plain_language_meaning="Public K–12 schools receiving federal education assistance would have to report foreign funding and contracts above an aggregate $10,000 threshold to the Department of Education within 30 days, including the source and relevant terms.",
        limitations=["The $10,000 trigger is measured in the aggregate for funds from, or contracts with, a foreign source as specified by the bill."],
        source_id="congress-text:119:hr:1005:eh", locator="section 2, XML id H50BB81EEBEEC49EEA19715316399E3A3",
        house_action_outcome="passed_house_242_176", legacy_assessment="revision_would_be_required",
    ),
    "house:119:1:313": draft(
        policy_choice="Whether to generally bar federal education-program funds from elementary and secondary schools receiving specified Chinese-government-backed partnerships or resources, with a waiver for qualifying pre-enactment contracts through contract termination.",
        mechanism_type="funding prohibition with pre-existing-contract waiver",
        mechanism="A prohibition on funds under covered federal education programs, effective one year after enactment, with discretionary Secretary of Education waivers for qualifying pre-enactment contracts until those contracts terminate.",
        affected_entities=["elementary schools", "secondary schools", "federal education programs", "Chinese-government-backed cultural or language institutes", "Chinese-government-supported persons and entities"],
        direct_effect="The proposal would generally prohibit covered federal education funds for a school that partners with a Chinese-government-funded cultural or language institute, operates a supported learning center, or receives specified teaching materials, personnel, funds, or other resources from someone acting for that government. The Secretary could waive the prohibition for a qualifying pre-enactment contract from the prohibition's effective date through contract termination.",
        plain_language_meaning="K–12 schools would generally lose access to covered federal education funds if they maintain specified partnerships or receive specified resources backed directly or indirectly by the Chinese government. Schools with qualifying pre-existing contracts could receive a waiver lasting until the contract ends.",
        limitations=["The restriction applies to the bill's defined federal education programs and covered forms of support, not every school resource or foreign relationship.", "The waiver is discretionary, not automatic: a covered contract must take effect before enactment and continue beyond the prohibition's effective date. The school must timely submit the complete unredacted contract, an English translation if needed, and a statement demonstrating benefit to its mission and students and promotion of U.S. security, stability, and economic vitality."],
        source_id="congress-text:119:hr:1069:eh", locator="section 2(a)-(c): prohibition, effective date, and qualifying-contract waiver; XML id H6C1C76CBDDE14D59ADF4ABE1B2458AAF",
        house_action_outcome="passed_house_247_164", legacy_assessment="revision_would_be_required",
    ),
    "house:119:1:314": draft(
        policy_choice="Whether to condition federal K–12 education funds on giving parents access to information about specified foreign-funded school materials, personnel, donations, agreements, and transactions.",
        mechanism_type="funding condition and disclosure rights",
        mechanism="A condition on Elementary and Secondary Education Act funding requiring local educational agencies and schools to answer parent requests and publish annual notice of those rights.",
        affected_entities=["local educational agencies", "public elementary and secondary schools", "parents", "State educational agencies", "Secretary of Education", "foreign countries and defined foreign entities of concern"],
        direct_effect="The proposal would require funded schools to let parents review specified foreign-funded curricular or staff-development materials and, within 30 days of a request, disclose covered staff compensation, donations, written agreements, and financial transactions; schools would also publish notice of these rights each year.",
        plain_language_meaning="Schools receiving federal K–12 funds would have to give parents a defined way to inspect materials and obtain information about specified foreign funding and agreements, with 30-day response deadlines and annual public notice.",
        limitations=["The disclosure rights cover the foreign sources and materials defined by the bill and remain subject to copyright law."],
        source_id="congress-text:119:hr:1049:eh", locator="section 2 / proposed ESEA section 8549D, XML ids H47071BF9C9D54B9197BE01DAAB7D03BB and HF6C6F29E14FC43118F54CB9BE7B91414",
        house_action_outcome="passed_house_247_166", legacy_assessment="revision_would_be_required",
    ),
    "house:119:1:315": draft(
        policy_choice="Whether to extend the Secure Rural Schools program's payments and related county project authorities through fiscal year 2026, including adjustments for fiscal years 2024 and 2025.",
        mechanism_type="reauthorization and payment extension",
        mechanism="Date extensions and payment-adjustment rules in the Secure Rural Schools and Community Self-Determination Act, plus extension of resource-advisory-committee authority.",
        affected_entities=["states and eligible counties containing federal land", "resource advisory committees", "federal land-management agencies"],
        direct_effect="The proposal would extend secure payments to eligible states and counties through fiscal year 2026, require adjustments where earlier 25-percent payments overlap with fiscal years 2024 or 2025 payments, and extend county project and resource-advisory-committee authorities.",
        plain_language_meaning="The federal-land county-payment program would continue through fiscal year 2026, with rules reconciling earlier payments and continuing related local project and advisory-committee authorities.",
        limitations=["The measure extends a federal-land and county-payment program; it is not a general education-funding program."],
        source_id="congress-text:119:s:356:es", locator="sections 2-3, XML ids id27be8195-a6ad-41fe-be2b-f80d7fd3c0fa and id6ccda971b16740b7ba843feb3f4aa7b2",
        house_action_outcome="passed_house_399_5", legacy_assessment="sufficient_unchanged",
    ),
    "house:119:1:332": draft(
        policy_choice="Whether to nullify the executive order issued on March 27, 2025 and named in the bill, prohibit funds to implement it, and preserve covered collective-bargaining agreements already in effect.",
        mechanism_type="executive-order nullification and agreement preservation",
        mechanism="A statutory declaration that the executive order has no force or effect, a funding prohibition on carrying it out, and continued effect for covered agreements.",
        affected_entities=["executive branch federal agencies", "federal employees", "labor organizations representing federal employees", "existing federal collective-bargaining agreements"],
        direct_effect="The proposal would nullify the named executive order, prohibit federal funds from being used to implement it, and require collective-bargaining agreements in effect on March 26, 2025 to remain effective through their stated terms.",
        plain_language_meaning="The March 27, 2025 executive order named in the bill would be cancelled and federal funding to implement it would be barred. Covered union agreements in effect on March 26, 2025 would remain in force through their stated terms.",
        limitations=["Source verification is required: request the official March 27, 2025 Executive Order titled Exclusions from Federal Labor-Management Relations Programs as governed evidence, with source identity, digest, and locators for its operative exclusions. The governed bill text establishes nullification, the funding bar, and agreement preservation, but does not establish which workplaces or agencies the order excluded; that underlying detail is withheld pending governed evidence."],
        source_id="congress-text:119:hr:2550:eh", locator="sections 2-3, XML ids HD9482AE3321245538430DB78AAECF758 and HAE68534AF56A4EC3B9DEE4F6E44FFB5C",
        house_action_outcome="passed_house_231_195", legacy_assessment="source_enrichment_required", candidate_state="source_enrichment_required",
    ),
    "house:119:1:68": draft(
        policy_choice="Whether to extend to ten years the time for specified criminal prosecutions and civil enforcement actions involving fraud in named pandemic unemployment programs and rescind $5 million in unobligated funds.",
        mechanism_type="limitations-period extension and rescission",
        mechanism="CARES Act amendments creating ten-year enforcement periods for specified fraud offenses, paired with a $5 million rescission.",
        affected_entities=["federal and state fraud-enforcement authorities", "people or entities subject to specified pandemic unemployment fraud actions", "pandemic unemployment programs"],
        direct_effect="The proposal would extend the limitations period for listed criminal and civil fraud actions involving covered pandemic unemployment claims to ten years and rescind $5 million in unobligated funds.",
        plain_language_meaning="Authorities would have up to ten years to bring the specified fraud cases tied to named pandemic unemployment programs, and the bill would cancel $5 million in unused funding.",
        limitations=["The extension applies only to the statutes and pandemic unemployment programs listed in the bill and does not revive a case whose limitations period had already expired before enactment."],
        source_id="congress-text:119:hr:1156:eh", locator="sections 2-3, XML ids H34C2230108EA480C897F5BF4FACDC16F and H18516DD3C2AC40A485B612ED6236E4E7",
        house_action_outcome="passed_house_295_127", legacy_assessment="revision_would_be_required",
    ),
    "house:119:1:79": draft(
        policy_choice="Whether to amend H.R. 1048's higher-education foreign gift and contract reporting provisions to streamline and align the reporting requirements, add noncompliance sanctions, and require negotiated rulemaking with stakeholder feedback.",
        mechanism_type="amendment to reporting, sanctions, and rulemaking provisions",
        mechanism="An exact amendment to H.R. 1048's Section 117 foreign gift and contract reporting provisions, as described in the governed Congress.gov amendment purpose.",
        affected_entities=["institutions of higher education subject to foreign gift and contract reporting", "Secretary of Education", "stakeholders participating in negotiated rulemaking"],
        direct_effect="The amendment would revise the bill's foreign gift and contract reporting rules to align them with other federal research-security compliance requirements, establish sanctions for noncompliance, and require the Secretary of Education to conduct negotiated rulemaking for stakeholder feedback.",
        plain_language_meaning="This narrower amendment would change how H.R. 1048 handled college foreign-funding reports, penalties for noncompliance, and rulemaking. It was not a vote on the entire H.R. 1048 package.",
        limitations=["Source enrichment is required: the governed exact-amendment record supplies only a purpose description, not the operative amendment text needed to explain the specific reporting changes, sanction triggers or amounts, and procedures. Those details are not invented.", "Parent-bill text does not supply the amendment meaning."],
        source_id="congress-amendment:119:hamdt:12", locator="structured fields officialDescription and purpose",
        house_action_outcome="failed_house_199_214", legacy_assessment="source_enrichment_required", boundary_type="amendment", candidate_state="source_enrichment_required",
    ),
    "house:119:1:83": draft(
        policy_choice="Whether to pass the full H.R. 1048 package changing higher-education disclosures and controls for foreign gifts, contracts, individual relationships, and specified investments.",
        mechanism_type="whole-package reporting duties, contract prohibition, waivers, and enforcement",
        mechanism="Higher Education Act amendments imposing institution and individual disclosures, prohibiting specified contracts subject to waivers, requiring investment reports, and establishing federal enforcement procedures.",
        affected_entities=["institutions of higher education", "covered faculty and staff", "Secretary of Education", "Attorney General", "foreign countries and entities defined by the bill"],
        direct_effect="The package would require new reports on covered foreign gifts, contracts, individual relationships, and investments; prohibit institutions from entering specified contracts with foreign countries or entities of concern unless waived; and establish investigation, civil-enforcement, and compliance duties.",
        plain_language_meaning="Colleges and universities would face expanded reporting and compliance rules for specified foreign money, contracts, individual ties, and investments. The package would also bar specified contracts unless a waiver applied and create enforcement procedures for noncompliance.",
        limitations=["This was a vote on the whole package. The candidate does not attribute the House action to any one component or to H.Amdt. 12."],
        source_id="congress-text:119:hr:1048:eh", locator="sections 2-5, including proposed HEA sections 117-117D, XML ids HCCD8409C14974C8881DD26701577F749 through H31745F232FA4477894372190F5DBA871",
        house_action_outcome="passed_house_241_169", legacy_assessment="revision_would_be_required",
    ),
    "house:119:2:184": draft(
        policy_choice="Whether to condition federal K–12 education funding on parental consent before specified school-record or accommodation changes for minors and prohibit use of those funds to teach or advance the bill's referenced definition of gender ideology.",
        mechanism_type="funding condition and use-of-funds prohibition",
        mechanism="Conditions and prohibitions attached to Elementary and Secondary Education Act funding.",
        affected_entities=["public elementary and middle schools receiving ESEA funds", "minor students", "parents", "local educational agencies"],
        direct_effect="The proposal would require funded schools to obtain parental consent before changing a covered minor's gender markers, pronouns, preferred name on school forms, or sex-based accommodations, and would prohibit use of ESEA funds to teach or advance concepts covered by the referenced definition.",
        plain_language_meaning="Public elementary and middle schools receiving federal K–12 funds would need parental consent for the specified record or accommodation changes involving minors. The same package would bar use of those federal funds for instruction covered by its referenced gender-ideology definition.",
        limitations=["Source enrichment is required: the governed bill text refers to Section 2 of Executive Order 14168 for the instructional-prohibition definition, but that definition is not present in this governed packet. The parental-consent rule is concrete; the full scope of the instructional prohibition cannot be explained from these sources alone.", "This is a whole-package choice containing two distinct funding conditions; neither is projected onto a separate component action."],
        source_id="congress-text:119:hr:2616:eh", locator="sections 2-3, XML ids HCC7E6915BD684958BCB5967F4695A797 and HF2E66708E0BA4CDA8AC5BA0779E27154",
        house_action_outcome="passed_house_217_198", legacy_assessment="source_enrichment_required", candidate_state="source_enrichment_required",
    ),
    "house:119:2:19": draft(
        policy_choice="Whether to let specified voluntary, outside-hours employee education or training time be excluded from compensable hours worked, including qualifying supplemental apprenticeship instruction.",
        mechanism_type="Fair Labor Standards Act hours-worked exclusion",
        mechanism="An amendment to federal wage-and-hour rules defining when education or training time may be excluded from hours worked.",
        affected_entities=["employees attending education or training", "employers", "participants in bona fide apprenticeship programs"],
        direct_effect="The proposal would permit employers to exclude education or training time from hours worked when it occurs outside regular hours, participation is voluntary without adverse action for declining, and no work is performed; it would also permit exclusion of qualifying supplemental apprenticeship instruction.",
        plain_language_meaning="Specified voluntary training outside regular work hours would not have to count as paid working time when the bill's conditions were met. Qualifying supplemental classroom instruction connected to a bona fide apprenticeship could also be excluded.",
        limitations=["The governed source is the official House-section Congressional Record at H677-H678 because no House-engrossed text exists for the failed passage; floor advocacy is not used as semantic evidence."],
        source_id="congressional-record:2026-01-13:house-section:H663-H719:hr2262", locator="House pages H677-H678, Section 2 of the modified committee substitute",
        house_action_outcome="failed_house_209_215", legacy_assessment="sufficient_unchanged",
    ),
    "house:119:2:216": draft(
        policy_choice="Whether to require maintaining current wages, hours, and employment terms pending agreement, continue an employer's bargaining duty unless the employee representative is decertified, and impose a first-contract bargaining, mediation, and binding-arbitration timetable.",
        mechanism_type="employment-term maintenance, continuing bargaining duty, deadlines, and binding arbitration",
        mechanism="National Labor Relations Act amendments requiring current wages, hours, and employment terms to be maintained pending agreement and continuing an employer's bargaining duty absent decertification following an election. First-contract bargaining must begin within 10 days, mediation may be requested after 90 days without agreement, and unresolved disputes go to a three-person arbitration panel 30 days after the mediation request, subject to agreed extensions.",
        affected_entities=["employers", "unions and other employee representatives, including newly recognized or certified representatives", "represented employees", "Federal Mediation and Conciliation Service", "three-person arbitration panels"],
        direct_effect="The proposal would require maintaining current wages, hours, and terms and conditions of employment pending agreement and continuing an employer's bargaining duty unless the representative is decertified following an election. For first contracts, the parties must begin bargaining within 10 days of a written request; after 90 days of bargaining without agreement either party could request federal mediation, and after 30 days from that request without agreement the dispute would go to arbitration. The parties may agree to longer periods, and the panel's award would bind them for two years unless amended by their written consent.",
        plain_language_meaning="Current wages, hours, and employment terms would have to be maintained while an agreement is pending, and employers would have to keep bargaining unless an election removes the employee representative's certification. First-contract talks would start within 10 days of a written request, allow mediation after 90 days without agreement, and move to arbitration after 30 days from the mediation request, subject to agreed extensions. The arbitration award would bind the parties for two years unless both agreed in writing to amend it.",
        limitations=["The timetable applies to initial collective-bargaining agreements; the employment-term maintenance and continuing bargaining duties are separate amendments to the general bargaining provision. The candidate does not predict when agreement would be reached or what terms would result.", "Section 4's GAO report on the time from recognition or certification to a first contract is treated as ancillary and non-material to this action explanation; it is omitted from the operative synthesis."],
        source_id="congress-text:119:hr:5408:eh", locator="section 3(1)(C)-(D) and (K), proposed NLRA sections 8(d)(1) and 8(d)(3), XML id HEDEFCE7BF6DD47D0AEC64B61FF47F8FF; ancillary reporting in section 4, XML id HF1A5274BD1D247FE9B8166CB448EDA50",
        house_action_outcome="passed_house_230_193", legacy_assessment="revision_would_be_required",
    ),
    "house:119:2:217": draft(
        policy_choice="Whether to require identity-fraud screening of every FAFSA filed on or after October 1, 2026 and additional verification before aid is disbursed when an application triggers reasonable suspicion.",
        mechanism_type="screening, notification, verification, and program-review duties",
        mechanism="Higher Education Act requirements for Department screening, applicant and school notices, institutional identity verification before disbursement, records, guidance, reports, and program-review prioritization.",
        affected_entities=["FAFSA applicants", "Secretary of Education", "institutions of higher education", "applicants flagged for reasonable suspicion of identity fraud"],
        direct_effect="The proposal would require the Department of Education to screen each covered FAFSA, notify flagged applicants and their selected schools, and require a school to verify identity by an approved method before disbursing federal student aid; repeated noncompliant disbursements would become a program-review priority.",
        plain_language_meaning="Every FAFSA filed from October 1, 2026 would be screened for indicators of identity fraud. If an application were flagged, a college could not release federal aid until it completed an approved identity check and notified the Department.",
        limitations=["A reasonable-suspicion flag triggers verification and notice; the proposal does not itself establish that the applicant committed fraud."],
        source_id="congress-text:119:hr:7892:eh", locator="sections 2-3, XML ids HA6F230CF82EF442E9ED3D3A20F0CEF49 and HC249CEAFE40A4C99A588EB81F69CDEA8",
        house_action_outcome="passed_house_249_172", legacy_assessment="revision_would_be_required",
    ),
    "house:119:2:31": draft(
        policy_choice="Whether to pass a four-division package changing ERISA retirement-plan rules for investment factors, service-provider selection, shareholder rights, and brokerage-window disclosures.",
        mechanism_type="whole-package fiduciary requirements, prohibitions, disclosures, and study",
        mechanism="Employee Retirement Income Security Act amendments plus a Government Accountability Office study requirement.",
        affected_entities=["ERISA retirement-plan fiduciaries", "plan participants and beneficiaries", "plan service providers", "defined-contribution plans", "Government Accountability Office"],
        direct_effect="The package would require retirement-plan investment decisions generally to rest on financial risk and return, prohibit sacrificing return or taking extra risk for nonfinancial goals, require provider selection without regard to race, color, religion, sex, or national origin, require shareholder-rights decisions to serve financial interests, and require notices before transactions outside the plan's designated investment options.",
        plain_language_meaning="Private retirement-plan managers would generally have to base investments and shareholder-rights decisions on financial interests, while following new provider-selection rules. Participants using investments outside the plan's designated options would receive required notices, and GAO would compare returns from those arrangements with other plan options.",
        limitations=["The investment rule allows documented nonfinancial tie-breakers when financial factors cannot distinguish alternatives, subject to the bill's conditions. This is an indivisible whole-package choice across four divisions; the candidate does not attribute the House action to any single component."],
        source_id="congress-text:119:hr:2988:eh", locator="sections 1002, 2002, 3002, and 4002-4003, XML ids H1CD8155FC8AF4951889A4BE3461BDAD3 through H8AA5D45D91CC43AEAAEAD1E27EC92108",
        house_action_outcome="passed_house_213_205", legacy_assessment="revision_would_be_required",
    ),
    "house:119:2:47": draft(
        policy_choice="Whether to require colleges participating in federal student-aid programs to distribute specified information about rights, accommodations, complaint channels, and resources for pregnant students who carry a pregnancy to term.",
        mechanism_type="information-disclosure duty",
        mechanism="A Higher Education Act condition requiring annual email, handbook, orientation, health or counseling center, and public-website dissemination.",
        affected_entities=["institutions of higher education participating in federal student-aid programs", "prospective and enrolled pregnant students", "Department of Education"],
        direct_effect="The proposal would require covered colleges to provide specified campus and community resource lists, accommodation information, and Title IX complaint instructions through annual emails and designated student-information channels.",
        plain_language_meaning="Colleges in federal student-aid programs would have to tell prospective and enrolled students where pregnant students carrying a pregnancy to term can find specified resources and accommodations and how to file certain discrimination complaints.",
        limitations=["The bill states that it does not authorize the Secretary to require additional information or create additional rights beyond those listed."],
        source_id="congress-text:119:hr:6359:eh", locator="section 2 / proposed HEA section 485(n), XML id H293C48F14DF34F72A87E034E1D8383D0",
        house_action_outcome="passed_house_217_211", legacy_assessment="revision_would_be_required",
    ),
    "house:119:2:82": draft(
        policy_choice="Whether to require public colleges receiving Higher Education Act assistance to charge qualifying U.S. nationals who reside in specified territories no more than the in-state tuition and fee rate.",
        mechanism_type="funding-linked tuition eligibility rule",
        mechanism="A Higher Education Act requirement limiting tuition and fees charged by assisted public institutions.",
        affected_entities=["public institutions of higher education receiving Higher Education Act assistance", "qualifying U.S. nationals residing in Guam, the Northern Mariana Islands, American Samoa, or the U.S. Virgin Islands"],
        direct_effect="The proposal would prohibit a covered public college from charging a qualifying resident of one of the four named territories more tuition or fees than it charges residents of the state where the college is located.",
        plain_language_meaning="Qualifying U.S. nationals from Guam, the Northern Mariana Islands, American Samoa, and the U.S. Virgin Islands would receive in-state tuition and fee rates at covered public colleges.",
        limitations=["Eligibility is limited to the territorial residents and U.S. nationals defined by the bill and to public institutions receiving assistance under the Higher Education Act."],
        source_id="congress-text:119:hr:6472:eh", locator="section 2 / proposed HEA section 135A, XML ids H5E1A85CA91CD4131A0CB1E160AD44B90 and H67A143521C7346D4B4F15971973560DD",
        house_action_outcome="passed_house_351_72", legacy_assessment="sufficient_unchanged",
    ),
}
