"""Detached model-authored proposals. Imported only by explicit candidate freeze."""

from backend.app.semantic_ir.m14c_source_hold_closure import AM, EO51, EO68, HEA

# References identify a source and its deterministic excerpt index; 'bill' binds
# the unchanged legacy operative-bill locator. They do not confer acceptance.
A = [(AM, i) for i in range(7)]
E = [(EO51, i) for i in range(4)]
G = [(EO68, 0)]
B = [("bill", 0)]

DRAFTS = {
    "house:119:1:79": {
        "policy_choice": "Whether to replace the bill with an exact substitute rewriting college foreign-gift and contract disclosures: annual reporting thresholds, public reports, equivalent-report alternatives, compliance duties and fines, specified exclusions, and negotiated rules aligned with other federal research-security reporting.",
        "mechanism": {"type": "substitute amendment: disclosure duties, exceptions, fines, and negotiated rulemaking",
                      "description": "The amendment would replace the bill's text and rewrite Higher Education Act Section 117. It would set reporting thresholds and deadlines, a public database, alternative-report and correction procedures, compliance responsibilities, financial sanctions, and defined exclusions; the Secretary must begin negotiated rulemaking within one year, and the rewritten Section 117 takes effect when those regulations take effect."},
        "affected_entities": ["institutions of higher education, including individual campuses of multicampus institutions", "institutions substantially owned or controlled by foreign sources", "institution-affiliated entities such as research foundations", "Department of Education", "foreign gift and contract sources"],
        "direct_effect": "Institutions would report by July 31 of the following year when gifts and contracts from one foreign source reach $100,000 in a calendar year or $250,000 over the previous three calendar years. Institutions substantially owned or controlled by foreign sources would report annually, including foreign gifts and contracts regardless of value; restricted or conditional gifts and contracts require additional disclosures. The Secretary would publish searchable, downloadable reports within 60 days of submission, allow equivalent state or federal reports and corrections, and could impose specified fines or compliance plans for noncompliance. Defined payments and transactions are excluded. Negotiated rules must address research-security reporting alignment, confidentiality, affiliated entities, structured gifts and contracts, and national-security-risk research; the rewritten disclosure section becomes effective with those rules.",
        "plain_language_meaning": "This substitute would require colleges to report foreign gifts and contracts at $100,000 in one year or $250,000 over three years from the same source, while requiring broader disclosures from institutions substantially owned or controlled by foreign sources and for restricted gifts. Reports would become publicly searchable, equivalent state or federal reports could substitute, and specified noncompliance could bring fines or a compliance plan. The proposal includes payment and transaction exclusions and requires negotiated rules to coordinate reporting with other federal research-security requirements before the rewritten disclosure section takes effect.",
        "field_refs": {"policy_choice": A, "mechanism": A, "affected_entities": [A[0], A[5]], "direct_effect": A, "plain_language_meaning": A},
        "limitations": [
            ("This is the printed substitute amendment, not the parent bill's meaning. It replaces page 1, line 1 through page 60, line 6; adoption at the amendment stage would not itself enact the substitute.", A),
            ("Reports identify amounts, source/country and purpose or intended use. Institutions must retain agreement copies until the latest of four years after agreement, termination, or applicable state retention requirements; produce them for audits or investigations; and translate contracts as applicable. Restricted or conditional gifts also require amounts, dates, conditions, and specified source-country information.", [A[0], A[1]]),
            ("A state or other federal report can replace the disclosure report only if it contains all required information for the same or an equivalent period; state assurances may be required. Institutions must be able to revise past reports to correct errors.", [A[2]]),
            ("For a knowing or willful disclosure or agreement-copy/translation violation, the Secretary may impose $250 to 50% of the gift or contract amount; three consecutive years permit an additional fine of $100,000 to the gift or contract amount. Knowing or willful foreign-ownership-report violations can incur up to 25% of Higher Education Act funding excluding Title IV student aid, with an additional fine subject to the same 25% cap for three consecutive years of violations. Administrative errors lasting three consecutive years can incur $250 to 50% of the gift or contract amount; two consecutive years without the required gift/contract report can trigger a compliance plan. These are the printed statutory bounds, not a prediction of penalties imposed.", [A[3]]),
            ("Excluded transactions include student-attendance payments or scholarships from a natural person acting individually, not for another person or entity except the student, without another contract beyond the institution-student attendance agreement; specified intellectual-property licensing or technical assistance not identified as a national-security risk; and funds solely for clinical trials. A U.S.-located institution's purchases of property or services from a foreign source are outside the contract definition. Gifts and contracts through an institution's supporting entities are included. Restricted or conditional gifts/contracts include terms concerning faculty employment, academic or research units/programs, student selection/admission, or aid restricted by the listed country, religion, sex, ethnic-origin or political-opinion categories.", [A[5]]),
            ("The amendment also incorporates HEA487(e)(2)(B)(ii) gift exceptions: loan/default-prevention/financial-literacy materials and programs; qualifying professional-training food, refreshments and materials; comparable student-employee loan benefits; institution-controlled, non-promotional loan counseling; specified lender/servicer/guarantor philanthropy or contributions without a loan-related advantage; and state-administered education aid. These categories retain the conditions in the incorporated statute, governed here in its 2024 U.S. Code edition.", [A[5], (HEA, 0)]),
            ("Institutions must designate a compliance officer, and the Department must maintain an internal, conflict-free contact for compliance assistance and database improvements. Data sharing with outside persons, including political appointees and personnel detailed from other agencies, is limited to expressly authorized or public information. Database user-group composition and meeting mechanics are ancillary to the explanation, not absent from the governed evidence.", [A[4], A[5]]),
            ("Negotiated rules must align with other agencies' reporting under the CHIPS Act, the Research and Development, Competition, and Innovation Act, and OSTP guidance including the specified NSPM-33 implementation guidance. Alignment is a rulemaking duty, not an assertion that all reporting regimes become identical. The substitute links Section 117's effective date to the regulations and separately specifies a database deadline relative to the first July 31 after enactment; this candidate does not invent a resolution of that timing interaction.", [A[1], A[6]]),
        ],
    },
    "house:119:1:332": {
        "policy_choice": "Whether to nullify Executive Order 14251, undoing its exclusions of named agencies and subdivisions from federal civil-service and Foreign Service labor-management coverage, bar funds to implement that order, and preserve covered collective-bargaining agreements in effect on March 26, 2025.",
        "mechanism": {"type": "executive-order nullification, funding prohibition, and agreement preservation",
                      "description": "H.R.2550 would give the March 27, 2025 order no force or effect and prohibit implementation funding. The order excludes named bodies from Title 5 Chapter 71 and specified State/USAID subdivisions from Title 22 Chapter 52 Subchapter X labor-management coverage, with exceptions and delegated powers. The bill separately keeps March 26, 2025 agency-union agreements effective through their stated terms."},
        "affected_entities": ["named executive-branch agencies and subdivisions", "federal civil-service employees and covered Foreign Service subdivisions", "labor organizations representing federal employees", "agencies and unions with collective-bargaining agreements in effect March 26, 2025"],
        "direct_effect": "The proposal would nullify EO14251's removal of named agencies and subdivisions from the federal civil-service labor-management statute and specified State Department and USAID units from the Foreign Service labor-management statute. Nullification would also remove this order's delegations and its directions to end specified agency participation in labor proceedings and reassign employees from non-agency business after agreement termination. Federal funds could not implement the order, and covered agency-union agreements in effect on March 26, 2025 would remain effective through their stated terms.",
        "plain_language_meaning": "The bill would cancel the order excluding major federal departments and specified other agencies or units from statutory labor-management coverage, including collective-bargaining arrangements, and excluding specified State Department and USAID units from the Foreign Service system. It would bar spending to implement that order and separately preserve covered union agreements already in effect on March 26, 2025 until their stated end dates.",
        "field_refs": {"policy_choice": B + E[:2], "mechanism": B + E, "affected_entities": B + E[:2], "direct_effect": B + E, "plain_language_meaning": B + E[:2]},
        "limitations": [
            ("Title 5 exclusions cover State, Defense, Treasury except the Bureau of Engraving and Printing, Veterans Affairs, Justice, Energy except FERC, EPA, USAID, NRC, NSF, USITC, FCC, and GSA. They also cover listed HHS, DHS, Interior and Agriculture units, Commerce's International Trade Administration, and specified information-resource-management offices across executive departments, SSA and OPM. The exact subdivisions are retained in the structured source excerpts, not generalized to all employees of every listed department.", [E[0]]),
            ("The order retains Chapter 71 coverage for immediate local employing offices of police officers, security guards and firefighters, except the Bureau of Prisons, and for specified Marshals Service subdivisions. Defense and VA secretaries could restore coverage to subdivisions through certified orders submitted for Federal Register publication within 15 days. Transportation received a separate, non-redelegable power to exclude subdivisions, including FAA, or suspend provisions for certain overseas activities after published determinations; the order does not itself exclude every Transportation employee.", [E[0], E[2]]),
            ("Foreign Service exclusions cover State subdivisions under the named senior offices plus embassies, consulates, diplomatic missions and consular offices, and USAID overseas missions/field offices and specified administrator/deputy-administrator subdivisions. The complete lists are in EO14251 section 3's structured excerpts.", [E[1]]),
            ("The order's directions about non-agency business and pending grievances, arbitral-award exceptions and unfair-labor-practice proceedings apply to affected employees upon termination of their agreements. Its 30-day agency-review report is ancillary to this action explanation. This candidate addresses what the bill would undo in this named order, not current agency execution, litigation outcomes, other orders, or a claim that all earlier labor exclusions disappear.", [E[3], *B]),
        ],
    },
    "house:119:2:184": {
        "policy_choice": "Whether to require parental consent before specified record or sex-based-accommodation changes for minors in elementary or middle grades, and separately bar ESEA funds from teaching or advancing concepts related to the definition of gender ideology incorporated from EO14168 section 2.",
        "mechanism": {"type": "parental-consent funding condition and separate use-of-funds prohibition by incorporated definition",
                      "description": "The bill conditions ESEA funding for public schools on parental consent for specified changes involving covered minors, and separately amends ESEA's prohibited uses of funds. That prohibition incorporates EO14168 section 2's definition, which concerns replacing sex as a category with self-assessed gender identity, identifying as a gender different from one's sex, and a spectrum of genders disconnected from sex."},
        "affected_entities": ["ESEA-funded public schools serving minors in elementary or middle grades", "covered minor students and their parents", "recipients and programs using ESEA funds"],
        "direct_effect": "Funded public schools would have to obtain parental consent before changing a covered minor's gender markers, pronouns or preferred name on a school form, or sex-based accommodations such as bathrooms or locker rooms. Separately, ESEA funds could not be used to teach or advance concepts related to the incorporated EO14168 definition: gender identity replacing sex as a category, people identifying as a gender different from their sex, a spectrum of genders disconnected from sex, and the concept of being born in the wrong-sexed body. The bill imports that definition from the order rather than creating an independent definition.",
        "plain_language_meaning": "Public schools receiving ESEA funds would need parental consent for specified school-form or bathroom/locker-room changes involving minors in elementary or middle grades. A separate rule would bar ESEA-funded teaching or advancement of concepts covered by EO14168's definition of gender ideology, including identity replacing sex as a category, identifying as a gender different from one's sex, a spectrum of genders separate from sex, and being born in the wrong-sexed body. These are the Executive Order's incorporated categories, not Political Fingerprint's judgments about gender.",
        "field_refs": {"policy_choice": B + G, "mechanism": B + G, "affected_entities": B, "direct_effect": B + G, "plain_language_meaning": B + G},
        "limitations": [
            ("The parental-consent clause is limited to minors in elementary or middle grades and the listed school-form changes or sex-based accommodations. The separate use-of-funds prohibition applies to ESEA funds and is not confined by that clause's definition of a covered student.", B),
            ("EO14168 section 2 defines sex as an unchangeable male/female biological classification and defines gender identity separately; subsection (f) supplies the incorporated gender-ideology definition. That definition also describes requiring institutions to recognize identification as a different sex as establishing that sex. This explanation attributes those classifications to the legal text, without adopting the order's evaluative descriptions or treating its rhetoric as established fact.", G),
            ("The bill prohibits teaching or advancing concepts related to the incorporated definition. It does not enumerate particular lessons, books or classroom scenarios; the candidate does not invent such applications. Incorporating this definition does not import all other Executive Order directives, and this whole-package choice is not projected onto separate component votes.", B + G),
        ],
    },
}
