"""Governed neutral M4A episode definitions derived from accepted action meaning."""

from __future__ import annotations


EPISODES = (
    (
        "laken-riley-detention-enforcement",
        "Laken Riley detention and State-enforcement path",
        "Whether to require detention and State enforcement remedies for covered inadmissible noncitizens connected to specified offenses.",
        ("house:119:1:6", "house:119:1:23"),
        {"house:119:1:6": "initial_passage", "house:119:1:23": "later_version"},
        "The House considered closely related House and Senate versions of the same detention-and-enforcement intervention.",
        "The later Senate version covers additional assault and serious-injury offenses.",
    ),
    (
        "born-alive-care-and-remedies",
        "Born-alive care, reporting, and remedies",
        "Whether to require specified care and reporting after an abortion or attempted abortion results in a child born alive and attach criminal and civil remedies.",
        ("house:119:1:27",),
        {},
        "One standalone final-passage choice.",
        "No other approved action presents the same care-and-remedies mechanism.",
    ),
    (
        "halt-fentanyl-legislative-path",
        "Classwide fentanyl scheduling legislative path",
        "Whether and under what conditions to make classwide Schedule I treatment, associated penalties, and research rules permanent.",
        ("house:119:1:32", "house:119:1:33", "house:119:1:166"),
        {
            "house:119:1:32": "amendment",
            "house:119:1:33": "initial_passage",
            "house:119:1:166": "later_version",
        },
        "The amendment modified H.R. 27 directly; H.R. 27 and S. 331 are successive versions of the same classwide scheduling and research framework.",
        "The amendment proposed a certification condition, and the later Senate framework was not textually identical to H.R. 27.",
    ),
    (
        "border-vehicle-flight-offense",
        "Border-area vehicle-flight offense",
        "Whether to create a federal offense and immigration consequences for intentionally fleeing specified pursuing officers near the border.",
        ("house:119:1:42",),
        {},
        "One standalone final-passage choice.",
        "No other approved action uses this border-area flight offense and penalty structure.",
    ),
    (
        "pandemic-unemployment-fraud-limitations",
        "Pandemic unemployment fraud limitations periods",
        "Whether to extend criminal and civil limitations periods for fraud involving specified pandemic unemployment programs.",
        ("house:119:1:68",),
        {},
        "One standalone final-passage choice.",
        "The later Treasury fraud-oversight action uses different institutions and mechanisms.",
    ),
    (
        "federal-injunction-remedy-scope",
        "Federal injunction remedy scope",
        "Whether generally to limit federal district-court injunctions to parties and represented nonparties while creating a multi-State exception.",
        ("house:119:1:98",),
        {},
        "One standalone final-passage choice.",
        "No other approved action changes this federal judicial-remedy rule.",
    ),
    (
        "law-enforcement-concealed-carry-expansion",
        "Law-enforcement concealed-carry expansion",
        "Whether to expand specified concealed-carry locations and qualification rules for current and retired law-enforcement officers while preserving an unresolved textual insertion.",
        ("house:119:1:128",),
        {},
        "The resolved carry-expansion provisions support a bounded standalone candidate; the separate textual insertion remains unresolved.",
        "The unresolved `any magazine and` insertion prevents a complete account of every provision.",
    ),
    (
        "retired-service-weapon-purchases",
        "Retired-service firearm purchases",
        "Whether to create a federal program for eligible officers to buy qualifying retired agency-issued firearms.",
        ("house:119:1:130",),
        {},
        "One standalone final-passage choice.",
        "This purchase program is distinct from concealed-carry and facility-carry rules.",
    ),
    (
        "officer-safety-data-reporting",
        "Officer safety and wellness reporting",
        "Whether to require Justice Department reports on attacks, data systems, aggression, and officer wellness resources.",
        ("house:119:1:131",),
        {},
        "One standalone final-passage choice.",
        "The action authorizes reporting, not the policies later informed by those reports.",
    ),
    (
        "dc-police-discipline-bargaining",
        "D.C. police discipline bargaining",
        "Whether to restore collective bargaining and prior limitations rules for discipline involving D.C. law-enforcement personnel.",
        ("house:119:1:162",),
        {},
        "One standalone D.C. institutional labor choice.",
        "Other D.C. measures concern different courts, offenses, bail, pursuits, or policing statutes.",
    ),
    (
        "dc-youth-offender-sentencing",
        "D.C. youth-offender sentencing",
        "Whether to narrow D.C. youth-offender eligibility, remove below-minimum sentencing authority, and require juvenile-crime statistics.",
        ("house:119:1:270",),
        {},
        "One standalone D.C. sentencing and reporting choice.",
        "The same-day juvenile-court transfer bill changes jurisdictional age thresholds rather than youth-offender sentencing.",
    ),
    (
        "dc-juvenile-court-transfer-age",
        "D.C. juvenile court transfer age",
        "Whether to lower age thresholds for excluding specified minors from D.C. Family Court jurisdiction and transferring covered proceedings.",
        ("house:119:1:271",),
        {},
        "One standalone D.C. juvenile-jurisdiction choice.",
        "The same-day youth-offender bill changes sentencing eligibility and statistics rather than court-transfer jurisdiction.",
    ),
    (
        "dc-judicial-nomination-commission",
        "D.C. judicial nomination structure",
        "Whether to terminate the D.C. Judicial Nomination Commission and reassign specified nomination and chief-judge functions.",
        ("house:119:1:274",),
        {},
        "One standalone D.C. judicial-administration choice.",
        "Other D.C. measures do not alter this nomination institution.",
    ),
    (
        "dc-police-pursuit-rules",
        "D.C. police pursuit rules",
        "Whether to replace D.C. pursuit restrictions with broader pursuit authority and specified exceptions.",
        ("house:119:1:275",),
        {},
        "One standalone D.C. pursuit-policy choice.",
        "Other D.C. policing actions alter discipline or repeal a broader reform statute.",
    ),
    (
        "vehicular-terrorism-assessment",
        "Vehicular-terrorism assessment",
        "Whether to require a Homeland Security assessment and congressional reporting on emerging vehicular-terrorism threats and countermeasures.",
        ("house:119:1:286",),
        {},
        "One standalone assessment-and-reporting choice.",
        "The cold-weather exercise action tests a different hazard and response mechanism.",
    ),
    (
        "epstein-records-disclosure",
        "Epstein records disclosure",
        "Whether to require release of specified Justice Department records concerning Jeffrey Epstein subject to enumerated withholding limits.",
        ("house:119:1:289",),
        {},
        "One standalone records-disclosure choice.",
        "No other approved action uses this disclosure mandate.",
    ),
    (
        "dc-pretrial-detention-cash-bail",
        "D.C. detention and secured cash bail",
        "Whether to require detention for defined D.C. offenses and secured cash bail for a separate set of offenses.",
        ("house:119:1:298",),
        {},
        "One standalone D.C. detention-and-bail choice.",
        "Federal bail-reporting and bail-bond false-statement measures use different mechanisms and jurisdictions.",
    ),
    (
        "dc-policing-reform-repeal",
        "D.C. policing reform repeal",
        "Whether to repeal most of D.C.'s 2022 policing reform law while retaining specified subtitles.",
        ("house:119:1:299",),
        {},
        "One standalone repeal choice.",
        "The retained subtitles and distinct contemporaneous D.C. bills prevent treating all D.C. policing measures as one path.",
    ),
    (
        "unaccompanied-child-placement-screening",
        "Unaccompanied-child placement screening",
        "Whether to require additional screening and secure-placement rules for specified unaccompanied children and sponsors.",
        ("house:119:1:340",),
        {},
        "One standalone placement-and-screening choice.",
        "This mechanism is distinct from the Laken Riley detention path.",
    ),
    (
        "minor-procedure-criminal-offenses",
        "Criminal offenses for specified procedures involving minors",
        "Whether to create federal offenses and exceptions for specified genital procedures, hormone administration, facilitation, and transport involving minors.",
        ("house:119:1:351",),
        {},
        "One standalone criminal-offense choice.",
        "No other approved action presents this covered-procedure and exception structure.",
    ),
    (
        "organized-retail-crime-coordination",
        "Organized retail crime enforcement and coordination",
        "Whether to expand specified theft and money-laundering rules and establish a time-limited coordination center for organized retail and supply-chain crime.",
        ("house:119:2:157",),
        {},
        "One standalone suspension-passage choice as amended.",
        "The action combines related enforcement and coordination mechanisms within one measure.",
    ),
    (
        "bail-bond-false-statements",
        "False statements in bail-bond business",
        "Whether to extend the federal insurance-business false-statement offense to specified monetary and immigration bail bonds.",
        ("house:119:2:169",),
        {},
        "One standalone bail-business offense choice.",
        "Other bail actions regulate release policy rather than false statements in bond business.",
    ),
    (
        "cashless-bail-jurisdiction-reporting",
        "Cashless-bail jurisdiction reporting",
        "Whether to require annual publication of jurisdictions using recognizance or unsecured-bond release for offenses identified by the Attorney General.",
        ("house:119:2:171",),
        {},
        "One standalone reporting choice.",
        "The action reports jurisdictional practices rather than directly setting D.C. detention rules.",
    ),
    (
        "federal-fraud-payment-integrity-oversight",
        "Federal fraud and payment-integrity oversight",
        "Whether to establish Treasury fraud-data functions, a permanent Inspector General, and expanded fraud-related data sharing.",
        ("house:119:2:218",),
        {},
        "One standalone institutional oversight choice.",
        "The earlier pandemic-unemployment action changes limitations periods rather than oversight institutions.",
    ),
    (
        "fisa-title-vii-short-term-extension",
        "FISA Title VII short-term extension",
        "Whether to extend two Title VII FISA sunset references from June 12 to July 2, 2026.",
        ("house:119:2:221",),
        {},
        "One bounded short-term extension with an unresolved possible predecessor reference to roll 155.",
        "Roll 155 has a preserved 110th/119th-Congress source-identity conflict and is not primary episode evidence.",
    ),
    (
        "senior-investor-exploitation-delays",
        "Senior investor exploitation transaction delays",
        "Whether to allow specified investment companies and transfer agents to delay redemptions when financial exploitation of a specified adult is reasonably suspected.",
        ("house:119:2:227",),
        {},
        "One standalone protective-delay choice as amended.",
        "No other approved action uses this financial-exploitation safeguard.",
    ),
    (
        "cold-weather-terrorism-response-exercise",
        "Cold-weather terrorism response exercise",
        "Whether to require a coordinated terrorism-response exercise involving extreme cold and cascading infrastructure failures.",
        ("house:119:2:234",),
        {},
        "One standalone exercise-and-reporting choice.",
        "The vehicular-terrorism action requires a different threat assessment rather than an exercise.",
    ),
    (
        "firearms-merchant-category-code-restrictions",
        "Firearms merchant-category-code restrictions",
        "Whether to bar firearm-retailer-specific merchant category code requirements and create a complaint, cure, and injunction process.",
        ("house:119:2:240",),
        {},
        "One standalone payment-network regulation choice.",
        "The measure regulates merchant coding rather than firearm possession, purchase eligibility, or facility carry.",
    ),
    (
        "defense-energy-infrastructure-certification",
        "Defense energy-infrastructure certification",
        "Whether to create a Defense certification and enforcement regime limiting specified State and local interference with covered energy infrastructure.",
        ("house:119:2:259",),
        {"house:119:2:259": "amendment"},
        "One standalone amendment to H.R. 8800 with a distinct energy-infrastructure mechanism.",
        "The no-safe final H.R. 8800 action cannot supply parent-package meaning; other amendments address unrelated mechanisms.",
    ),
    (
        "defense-facility-personal-firearm-process",
        "Defense-facility personal-firearm process",
        "Whether to create an individualized permission process for specified service members and Defense employees to carry personal firearms at covered facilities.",
        ("house:119:2:265",),
        {"house:119:2:265": "amendment"},
        "One standalone amendment to H.R. 8800 with a distinct facility-carry mechanism.",
        "The no-safe final H.R. 8800 action cannot supply parent-package meaning; other amendments address unrelated mechanisms.",
    ),
    (
        "military-chaplain-protections",
        "Military chaplain duties and protections",
        "Whether to codify specified military chaplain duties, religious protections, confidentiality, and enforcement consequences.",
        ("house:119:2:273",),
        {"house:119:2:273": "amendment"},
        "One standalone amendment to H.R. 8800 with a distinct chaplaincy mechanism.",
        "The no-safe final H.R. 8800 action cannot supply parent-package meaning; other amendments address unrelated mechanisms.",
    ),
    (
        "military-speed-camera-funding-ban",
        "Military-installation speed-camera funding ban",
        "Whether to bar federal support for automated speed-enforcement cameras on military installations subject to security-related exceptions.",
        ("house:119:2:275",),
        {"house:119:2:275": "amendment"},
        "One standalone amendment to H.R. 8800 with a distinct speed-enforcement mechanism.",
        "The no-safe final H.R. 8800 action cannot supply parent-package meaning; other amendments address unrelated mechanisms.",
    ),
)


INITIAL_REPLACEMENTS = {
    "dc-youth-offender-sentencing": None,
    "dc-juvenile-court-transfer-age": None,
    "fisa-title-vii-short-term-extension": None,
}


INITIAL_EXTRA_EPISODES = (
    (
        "dc-juvenile-justice-age-thresholds",
        "D.C. juvenile justice age thresholds",
        "Whether to narrow D.C. youth-treatment rules through age, sentencing, and court-transfer thresholds.",
        ("house:119:1:270", "house:119:1:271"),
        {},
        "The measures were considered together and both narrow youth-treatment rules.",
        "One changes youth-offender sentencing eligibility and reporting; the other changes Family Court jurisdiction and transfer ages.",
    ),
    (
        "fisa-title-vii-successive-extensions",
        "FISA Title VII successive extensions",
        "Whether to enact successive short-term extensions of two Title VII FISA sunset references.",
        ("house:119:2:155", "house:119:2:221"),
        {"house:119:2:155": "initial_passage", "house:119:2:221": "later_version"},
        "Both operative bodies describe successive short-term extensions of the same sunset references.",
        "Roll 155 retains a material source-identity conflict that may prevent treating it as a resolved predecessor.",
    ),
)


RELATED_LINEAGES = (
    (
        "laken-riley-versions",
        "near_duplicate_legislative_versions",
        ("house:119:1:6", "house:119:1:23"),
        "House and Senate versions of the same named detention-and-enforcement legislation.",
    ),
    (
        "halt-fentanyl-parent",
        "amendment_parent",
        ("house:119:1:32", "house:119:1:33"),
        "Roll 32 amended H.R. 27 before the roll 33 passage choice.",
    ),
    (
        "halt-fentanyl-successor",
        "predecessor_successor_framework",
        ("house:119:1:33", "house:119:1:166"),
        "H.R. 27 and S. 331 are successive classwide fentanyl scheduling and research frameworks.",
    ),
    (
        "fisa-short-extensions",
        "possible_predecessor_successor",
        ("house:119:2:155", "house:119:2:221"),
        "Operative dates and sunset references are successive, but roll 155 retains a source-identity conflict.",
    ),
    (
        "dc-juvenile-measures",
        "related_measure_family",
        ("house:119:1:270", "house:119:1:271"),
        "Same-day D.C. juvenile-justice measures with different sentencing and jurisdiction mechanisms.",
    ),
    (
        "dc-policing-family",
        "related_measure_family",
        ("house:119:1:162", "house:119:1:275", "house:119:1:299"),
        "D.C. policing measures with distinct labor, pursuit, and statutory-repeal mechanisms.",
    ),
    (
        "bail-policy-family",
        "related_policy_family",
        ("house:119:1:298", "house:119:2:169", "house:119:2:171"),
        "Bail-related measures with distinct D.C. detention, bond-business offense, and reporting mechanisms.",
    ),
    (
        "pandemic-fraud-family",
        "related_policy_family",
        ("house:119:1:68", "house:119:2:218"),
        "Fraud-control measures using distinct limitations-period and institutional oversight mechanisms.",
    ),
    (
        "terrorism-preparedness-family",
        "related_policy_family",
        ("house:119:1:286", "house:119:2:234"),
        "Threat-preparedness measures using distinct assessment and exercise mechanisms.",
    ),
    (
        "hr8800-parent-path",
        "shared_parent_measure",
        (
            "house:119:2:259",
            "house:119:2:265",
            "house:119:2:273",
            "house:119:2:275",
            "house:119:2:278",
        ),
        "Four distinct amendments share H.R. 8800 as parent; the final passage package remains no-safe.",
    ),
)
