// Generated by backend/scripts/build_blind_editorial_pipeline_validation.py.
// Review-only member overlay and inference; shared legislative facts remain in the Justice dossier.
export const blindEditorialPipelineValidationData = Object.freeze({
  "schemaVersion": "blind_editorial_generated_candidate_v1",
  "startingCommit": "7bce7467cebfde4fd2f164bdcecb596ba0fd1e91",
  "deterministicBuildIdentifier": "blind-editorial-pipeline-validation-v1@7bce7467cebfde4fd2f164bdcecb596ba0fd1e91",
  "selectionLock": "dedb3b9700df6a3e40107b838f34ee4c82ed88d55a3ac369dd9c0e192cb796c3",
  "selectedMember": {
    "member_id": "G000586",
    "member_display_name": "Jesús G. \"Chuy\" García",
    "action_vector": [
      "Nay",
      "Nay",
      "Nay",
      "Nay",
      "Nay",
      "Nay",
      "Nay"
    ],
    "novelty": {
      "distance_from_references": {
        "F000477": 3,
        "M001184": 4
      },
      "episode_signatures": {
        "halt-fentanyl-legislative-path": [
          "Nay",
          "Nay",
          "Nay"
        ],
        "retired-service-weapon-purchases": [
          "Nay"
        ],
        "officer-safety-data-reporting": [
          "Nay"
        ],
        "dc-police-pursuit-rules": [
          "Nay"
        ],
        "dc-policing-reform-repeal": [
          "Nay"
        ]
      },
      "episode_signatures_distinct_from_both_references": [
        "officer-safety-data-reporting"
      ],
      "candidate_minority_action_count": 0,
      "reference_minority_action_counts": [
        3,
        3
      ],
      "score_components": {
        "minimum_reference_distance": 3,
        "novel_episode_signature_count": 1,
        "action_balance_distance": 3,
        "total_reference_distance": 7
      }
    }
  },
  "overlay": {
    "schema_version": "editorial_member_overlay_v2",
    "member": {
      "bioguide_id": "G000586",
      "display_name": "Jesús G. \"Chuy\" García",
      "formal_name": "Mr. García of Illinois",
      "party": "D",
      "state": "IL",
      "district": "4th"
    },
    "reviewed_period": "119th Congress, February 6-November 19, 2025",
    "shared_episode_set": {
      "episode_set_id": "justice-public-safety-pr95-five-episodes",
      "version": "1.1.0",
      "episode_map_path": "docs/editorial/valerie_foushee_justice_public_safety_gold_v1/policy_episode_map.json",
      "expected_substantive_roll_ids": [
        32,
        33,
        130,
        131,
        166,
        275,
        299
      ],
      "expected_control_roll_ids": [
        160,
        161,
        267,
        268,
        290,
        291
      ],
      "expected_independent_episode_ids": [
        "halt-fentanyl-legislative-path",
        "retired-service-weapon-purchases",
        "officer-safety-data-reporting",
        "dc-police-pursuit-rules",
        "dc-policing-reform-repeal"
      ],
      "episode_rolls": {
        "halt-fentanyl-legislative-path": [
          32,
          33,
          166
        ],
        "retired-service-weapon-purchases": [
          130
        ],
        "officer-safety-data-reporting": [
          131
        ],
        "dc-police-pursuit-rules": [
          275
        ],
        "dc-policing-reform-repeal": [
          299
        ]
      }
    },
    "roll_actions": [
      {
        "roll": 32,
        "action": "Nay",
        "counting": true,
        "episode_id": "halt-fentanyl-legislative-path",
        "party_majority_action": "Yea",
        "aligned_with_party_majority": false,
        "source_id": "clerk_roll_032"
      },
      {
        "roll": 33,
        "action": "Nay",
        "counting": true,
        "episode_id": "halt-fentanyl-legislative-path",
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_033"
      },
      {
        "roll": 130,
        "action": "Nay",
        "counting": true,
        "episode_id": "retired-service-weapon-purchases",
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_130"
      },
      {
        "roll": 131,
        "action": "Nay",
        "counting": true,
        "episode_id": "officer-safety-data-reporting",
        "party_majority_action": "Yea",
        "aligned_with_party_majority": false,
        "source_id": "clerk_roll_131"
      },
      {
        "roll": 166,
        "action": "Nay",
        "counting": true,
        "episode_id": "halt-fentanyl-legislative-path",
        "party_majority_action": "Yea",
        "aligned_with_party_majority": false,
        "source_id": "clerk_roll_166"
      },
      {
        "roll": 275,
        "action": "Nay",
        "counting": true,
        "episode_id": "dc-police-pursuit-rules",
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_275"
      },
      {
        "roll": 299,
        "action": "Nay",
        "counting": true,
        "episode_id": "dc-policing-reform-repeal",
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_299"
      },
      {
        "roll": 160,
        "action": "Nay",
        "counting": false,
        "episode_id": null,
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_160"
      },
      {
        "roll": 161,
        "action": "Nay",
        "counting": false,
        "episode_id": null,
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_161"
      },
      {
        "roll": 267,
        "action": "Nay",
        "counting": false,
        "episode_id": null,
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_267"
      },
      {
        "roll": 268,
        "action": "Nay",
        "counting": false,
        "episode_id": null,
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_268"
      },
      {
        "roll": 290,
        "action": "Nay",
        "counting": false,
        "episode_id": null,
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_290"
      },
      {
        "roll": 291,
        "action": "Nay",
        "counting": false,
        "episode_id": null,
        "party_majority_action": "Nay",
        "aligned_with_party_majority": true,
        "source_id": "clerk_roll_291"
      }
    ],
    "episode_trajectories": [
      {
        "episode_id": "halt-fentanyl-legislative-path",
        "rolls": [
          32,
          33,
          166
        ],
        "action_signature": [
          "Nay",
          "Nay",
          "Nay"
        ],
        "coverage_status": "complete",
        "mechanism_family": "controlled-substance-scheduling",
        "relationship_to_repeated_stages": "Three related rolls are interpreted as one legislative trajectory and one independent episode.",
        "member_trajectory": "Opposed the certification condition, opposed the earlier House framework, and opposed the later permanent framework.",
        "practical_policy_direction": "One fentanyl trajectory with action signature Nay/Nay/Nay.",
        "theme_evidence": [
          {
            "theme_id": "fentanyl-episode-opposition",
            "rationale": "Opposed all three actions within the single fentanyl episode."
          },
          {
            "theme_id": "cross-mechanism-opposition",
            "rationale": "Opposed reviewed actions across distinct mechanisms."
          }
        ],
        "contrary_or_limiting_evidence": [],
        "package_vote_limitations": []
      },
      {
        "episode_id": "retired-service-weapon-purchases",
        "rolls": [
          130
        ],
        "action_signature": [
          "Nay"
        ],
        "coverage_status": "complete",
        "mechanism_family": "firearm-access",
        "relationship_to_repeated_stages": "",
        "member_trajectory": "Opposed the reviewed retired-service-firearm purchase program.",
        "practical_policy_direction": "Opposed the reviewed retired-service-firearm purchase program.",
        "theme_evidence": [
          {
            "theme_id": "limits-on-tools-authority-and-rollbacks",
            "rationale": "Opposed reviewed tool or authority expansions and safeguard rollbacks."
          },
          {
            "theme_id": "cross-mechanism-opposition",
            "rationale": "Opposed reviewed actions across distinct mechanisms."
          }
        ],
        "contrary_or_limiting_evidence": [],
        "package_vote_limitations": []
      },
      {
        "episode_id": "officer-safety-data-reporting",
        "rolls": [
          131
        ],
        "action_signature": [
          "Nay"
        ],
        "coverage_status": "complete",
        "mechanism_family": "data-reporting",
        "relationship_to_repeated_stages": "",
        "member_trajectory": "Opposed the reviewed officer-safety and wellness reporting bill.",
        "practical_policy_direction": "Opposed the reviewed officer-safety and wellness reporting bill.",
        "theme_evidence": [
          {
            "theme_id": "cross-mechanism-opposition",
            "rationale": "Opposed reviewed actions across distinct mechanisms."
          }
        ],
        "contrary_or_limiting_evidence": [],
        "package_vote_limitations": []
      },
      {
        "episode_id": "dc-police-pursuit-rules",
        "rolls": [
          275
        ],
        "action_signature": [
          "Nay"
        ],
        "coverage_status": "complete",
        "mechanism_family": "pursuit-authority",
        "relationship_to_repeated_stages": "",
        "member_trajectory": "Opposed the reviewed expansion of D.C. police-pursuit authority.",
        "practical_policy_direction": "Opposed the reviewed expansion of D.C. police-pursuit authority.",
        "theme_evidence": [
          {
            "theme_id": "limits-on-tools-authority-and-rollbacks",
            "rationale": "Opposed reviewed tool or authority expansions and safeguard rollbacks."
          },
          {
            "theme_id": "dc-policing-change-opposition",
            "rationale": "Opposed both reviewed D.C. policing policy proposals."
          },
          {
            "theme_id": "cross-mechanism-opposition",
            "rationale": "Opposed reviewed actions across distinct mechanisms."
          }
        ],
        "contrary_or_limiting_evidence": [],
        "package_vote_limitations": []
      },
      {
        "episode_id": "dc-policing-reform-repeal",
        "rolls": [
          299
        ],
        "action_signature": [
          "Nay"
        ],
        "coverage_status": "complete",
        "mechanism_family": "safeguard-repeal",
        "relationship_to_repeated_stages": "",
        "member_trajectory": "Opposed the reviewed repeal of most D.C. policing safeguards.",
        "practical_policy_direction": "Opposed the reviewed repeal of most D.C. policing safeguards.",
        "theme_evidence": [
          {
            "theme_id": "limits-on-tools-authority-and-rollbacks",
            "rationale": "Opposed reviewed tool or authority expansions and safeguard rollbacks."
          },
          {
            "theme_id": "dc-policing-change-opposition",
            "rationale": "Opposed both reviewed D.C. policing policy proposals."
          },
          {
            "theme_id": "cross-mechanism-opposition",
            "rationale": "Opposed reviewed actions across distinct mechanisms."
          },
          {
            "theme_id": "safeguard-repeal-opposition",
            "rationale": "Opposed the reviewed repeal of most D.C. policing safeguards."
          }
        ],
        "contrary_or_limiting_evidence": [],
        "package_vote_limitations": []
      }
    ],
    "coverage": {
      "substantive_rolls_expected": 7,
      "substantive_rolls_observed": 7,
      "substantive_yes_no_actions": 7,
      "present_actions": 0,
      "not_voting_actions": 0,
      "not_yet_serving_actions": 0,
      "no_longer_serving_actions": 0,
      "expected_in_service_actions": 7,
      "missing_actions": 0,
      "independent_episodes_expected": 5,
      "independent_episodes_complete": 5,
      "independent_episodes_partial": 0,
      "independent_episodes_missing": 0,
      "independent_episodes_outside_service": 0
    },
    "publication": {
      "editorial_status": "human_approval_pending",
      "benchmark_status": "not_promoted",
      "production_eligible": false
    }
  },
  "inference": {
    "schema_version": "editorial_member_inference_v2",
    "member": {
      "bioguide_id": "G000586",
      "display_name": "Jesús G. \"Chuy\" García",
      "formal_name": "Mr. García of Illinois",
      "party": "D",
      "state": "IL",
      "district": "4th"
    },
    "candidate_id": "uniform_direction_without_common_policy_rationale",
    "inference_level": "bounded_descriptive_pattern",
    "evidence_strength_label": "Uniform opposition across the reviewed proposals",
    "primary_conclusion": "Across the reviewed record, García of Illinois voted against all seven substantive proposals examined here. That included all three actions in the fentanyl episode, the officer-safety reporting bill, the retired-service-firearm program, broader D.C. pursuit authority, and repeal of most provisions of D.C.'s 2022 policing reform law. The vote direction is consistently oppositional, but the proposals span different—and sometimes substantively contrasting—policy approaches, so this record does not establish one overarching public-safety philosophy.",
    "assessment": "uniform_direction_without_common_policy_rationale",
    "support_balance": 5,
    "supporting_independent_episodes": [
      {
        "episode_id": "halt-fentanyl-legislative-path",
        "weight": 1,
        "rationale": "Recorded Nay action in this complete reviewed episode; direction is descriptive, not a shared policy rationale."
      },
      {
        "episode_id": "retired-service-weapon-purchases",
        "weight": 1,
        "rationale": "Recorded Nay action in this complete reviewed episode; direction is descriptive, not a shared policy rationale."
      },
      {
        "episode_id": "officer-safety-data-reporting",
        "weight": 1,
        "rationale": "Recorded Nay action in this complete reviewed episode; direction is descriptive, not a shared policy rationale."
      },
      {
        "episode_id": "dc-police-pursuit-rules",
        "weight": 1,
        "rationale": "Recorded Nay action in this complete reviewed episode; direction is descriptive, not a shared policy rationale."
      },
      {
        "episode_id": "dc-policing-reform-repeal",
        "weight": 1,
        "rationale": "Recorded Nay action in this complete reviewed episode; direction is descriptive, not a shared policy rationale."
      }
    ],
    "weakening_independent_episodes": [],
    "neutral_independent_episodes": [],
    "independent_episode_count": 5,
    "within_episode_trajectories": [
      {
        "episode_id": "halt-fentanyl-legislative-path",
        "relationship_to_repeated_stages": "Three related rolls are interpreted as one legislative trajectory and one independent episode.",
        "member_trajectory": "Opposed the certification condition, opposed the earlier House framework, and opposed the later permanent framework.",
        "practical_policy_direction": "One fentanyl trajectory with action signature Nay/Nay/Nay."
      }
    ],
    "repeated_cross_episode_themes": [
      {
        "theme_id": "dc-policing-change-opposition",
        "label": "D.C. policing change opposition",
        "finding": "Opposed both reviewed D.C. policing policy proposals.",
        "supporting_episodes": [
          {
            "episode_id": "dc-police-pursuit-rules",
            "mechanism_family": "police operational discretion",
            "rationale": "Opposed both reviewed D.C. policing policy proposals."
          },
          {
            "episode_id": "dc-policing-reform-repeal",
            "mechanism_family": "police oversight and accountability safeguards",
            "rationale": "Opposed both reviewed D.C. policing policy proposals."
          }
        ],
        "mechanism_families": [
          "police operational discretion",
          "police oversight and accountability safeguards"
        ],
        "editorially_defensible": true
      }
    ],
    "notable_one_off_choices": [
      {
        "episode_id": "officer-safety-data-reporting",
        "mechanism_family": "data-reporting",
        "practical_policy_direction": "Opposed the reviewed officer-safety and wellness reporting bill."
      },
      {
        "episode_id": "retired-service-weapon-purchases",
        "mechanism_family": "firearm-access",
        "practical_policy_direction": "Opposed the reviewed retired-service-firearm purchase program."
      }
    ],
    "one_off_or_unproven_themes": [
      {
        "theme_id": "fentanyl-episode-opposition",
        "label": "Fentanyl episode opposition",
        "finding": "Opposed all three actions within the single fentanyl episode.",
        "supporting_episodes": [
          {
            "episode_id": "halt-fentanyl-legislative-path",
            "mechanism_family": "controlled-substance scheduling, enforcement, and research access",
            "rationale": "Opposed all three actions within the single fentanyl episode."
          }
        ],
        "mechanism_families": [
          "controlled-substance scheduling, enforcement, and research access"
        ],
        "editorially_defensible": false,
        "not_repeated_reason": "Only one independent episode supplies this theme in the reviewed sample."
      },
      {
        "theme_id": "safeguard-repeal-opposition",
        "label": "Safeguard-repeal opposition",
        "finding": "Opposed the reviewed repeal of most D.C. policing safeguards.",
        "supporting_episodes": [
          {
            "episode_id": "dc-policing-reform-repeal",
            "mechanism_family": "police oversight and accountability safeguards",
            "rationale": "Opposed the reviewed repeal of most D.C. policing safeguards."
          }
        ],
        "mechanism_families": [
          "police oversight and accountability safeguards"
        ],
        "editorially_defensible": false,
        "not_repeated_reason": "Only one independent episode supplies this theme in the reviewed sample."
      }
    ],
    "contrary_or_limiting_evidence": [],
    "why_conclusion_does_not_go_further": "Uniform direction across heterogeneous proposals is descriptive and does not establish a shared policy rationale.",
    "future_expansion_rule": "Recompute from expanded member actions and shared episode annotations; new independent episodes may strengthen, narrow, contest, or replace this candidate.",
    "reviewed_period": "119th Congress, February 6-November 19, 2025",
    "human_review_status": "human_approval_pending",
    "coverage": {
      "substantive_rolls_expected": 7,
      "substantive_rolls_observed": 7,
      "substantive_yes_no_actions": 7,
      "present_actions": 0,
      "not_voting_actions": 0,
      "not_yet_serving_actions": 0,
      "no_longer_serving_actions": 0,
      "expected_in_service_actions": 7,
      "missing_actions": 0,
      "independent_episodes_expected": 5,
      "independent_episodes_complete": 5,
      "independent_episodes_partial": 0,
      "independent_episodes_missing": 0,
      "independent_episodes_outside_service": 0
    },
    "episode_references": [
      "halt-fentanyl-legislative-path",
      "retired-service-weapon-purchases",
      "officer-safety-data-reporting",
      "dc-police-pursuit-rules",
      "dc-policing-reform-repeal"
    ],
    "candidate_evaluation": [
      {
        "candidate_id": "conditional-guardrail-boundary",
        "eligible": false,
        "score": 3,
        "specificity": 10,
        "supporting_themes": [
          "limits-on-tools-authority-and-rollbacks"
        ],
        "conflicting_themes": []
      },
      {
        "candidate_id": "reviewed-enforcement-expansion",
        "eligible": false,
        "score": -1,
        "specificity": 8,
        "supporting_themes": [],
        "conflicting_themes": [
          "limits-on-tools-authority-and-rollbacks"
        ]
      },
      {
        "candidate_id": "police-authority-fentanyl-divide",
        "eligible": false,
        "score": 1,
        "specificity": 8,
        "supporting_themes": [
          "fentanyl-episode-opposition"
        ],
        "conflicting_themes": []
      },
      {
        "candidate_id": "national-action-dc-boundary",
        "eligible": false,
        "score": 2,
        "specificity": 10,
        "supporting_themes": [
          "dc-policing-change-opposition"
        ],
        "conflicting_themes": []
      },
      {
        "candidate_id": "broad-support-safeguard-exception",
        "eligible": false,
        "score": 1,
        "specificity": 14,
        "supporting_themes": [
          "safeguard-repeal-opposition"
        ],
        "conflicting_themes": []
      }
    ],
    "candidate_basis": {
      "basis_type": "uniform_action_direction",
      "substantive_theme_ids": [],
      "uniform_action_direction": {
        "direction": "Nay",
        "count": 7,
        "total": 7,
        "uniform": true
      }
    },
    "publication": {
      "editorial_status": "human_approval_pending",
      "benchmark_status": "not_promoted",
      "production_eligible": false
    }
  },
  "featuredEpisodeIds": [
    "halt-fentanyl-legislative-path",
    "retired-service-weapon-purchases",
    "officer-safety-data-reporting",
    "dc-police-pursuit-rules",
    "dc-policing-reform-repeal"
  ],
  "publication": {
    "editorial_status": "human_approval_pending",
    "benchmark_status": "not_promoted",
    "production_eligible": false
  }
});
